import t1 from "../pages/template/img/t1.svg";
import t2 from "../pages/template/img/t2.svg";
import td from "../pages/template/img/td.svg";

export const initialTemplate = {
	template: {
		1: { button: 1, background: 1, imgstyle: 1 },
		2: { button: 9, background: 4, imgstyle: 1 },
		3: { button: 8, background: 3, imgstyle: 2 },
		4: { button: 11, background: 2, imgstyle: 1 },
		5: { button: 17, background: 6, imgstyle: 2 },
		6: { button: 18, background: 7, imgstyle: 2 },
		7: { button: 10, background: 5, imgstyle: 2 },
		8: { button: 14, background: 8, imgstyle: 2 },
	},
	button: {
		1: "button button-1",
		2: "button button-1 radius1",
		3: "button button-1 radius2",
		4: "button button-2",
		5: "button button-2 radius1",
		6: "button button-2 radius2",
		7: "button button-3",
		8: "button button-3 radius1",
		9: "button button-3 radius2",
		10: "button button-4",
		11: "button button-4 radius1",
		12: "button button-4 radius2",
		13: "button btn--stripe",
		14: "button btn--stripe radius1",
		15: "button btn--stripe radius2",
		16: "button learn-more",
		17: "button learn-more radius1",
		18: "button learn-more radius2",
	},
	background: {
		1: "bg b1",
		2: "bg bg2",
		3: "bg bg3",
		4: "bg bg4",
		5: "bg bg5",
		6: "bg bg6",
		7: "bg bg7",
		8: "bg bg8",
	},
	imgstyle: {
		1: "img-rounded",
		2: "img-sequere",
	},
};

// export const initialTemplate2 = {
// 	template: {
// 		1: { button: 1, background: 1, imgstyle: 1 },
// 		2: { button: 9, background: 4, imgstyle: 1 },
// 		3: { button: 8, background: 3, imgstyle: 2 },
// 		4: { button: 11, background: 2, imgstyle: 1 },
// 		5: { button: 17, background: 6, imgstyle: 2 },
// 		6: { button: 18, background: 7, imgstyle: 2 },
// 		7: { button: 10, background: 5, imgstyle: 2 },
// 		8: { button: 14, background: 8, imgstyle: 2 },
// 	},
// 	button: [
// 		{
// 			1: "button button-1",
// 			2: "button button-1 radius1",
// 			3: "button button-1 radius2",
// 			4: "button button-2",
// 			5: "button button-2 radius1",
// 			6: "button button-2 radius2",
// 			7: "button button-3",
// 			8: "button button-3 radius1",
// 			9: "button button-3 radius2",
// 			10: "button button-4",
// 			11: "button button-4 radius1",
// 			12: "button button-4 radius2",
// 			13: "button btn--stripe",
// 			14: "button btn--stripe radius1",
// 			15: "button btn--stripe radius2",
// 			16: "button learn-more",
// 			17: "button learn-more radius1",
// 			18: "button learn-more radius2",
// 		},
// 	],
// 	background: {
// 		1: "bg b1",
// 		2: "bg bg2",
// 		3: "bg bg3",
// 		4: "bg bg4",
// 		5: "bg bg5",
// 		6: "bg bg6",
// 		6: "bg bg7",
// 		6: "bg bg8",
// 	},
// 	imgstyle: {
// 		1: "img-rounded",
// 		2: "img-sequere",
// 	},
// };
